# ML Lab-2

In [143]:
# Config for google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [144]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [145]:
df = pd.read_csv("/content/drive/MyDrive/Ml-LabData/Lab-2/Exercise-CarData.csv")
df.head()

Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
0           0  13500  23.0  46986  ...         0  2000  three    1165
1           1  13750  23.0  72937  ...         0  2000      3    1165
2           2  13950  24.0  41711  ...         0  2000      3    1165
3           3  14950  26.0  48000  ...         0  2000      3    1165
4           4  13750  30.0  38500  ...         0  2000      3    1170

[5 rows x 11 columns]

In [146]:
df.describe()

Unnamed: 0         Price  ...           CC      Weight
count  1436.000000   1436.000000  ...  1436.000000  1436.00000
mean    717.500000  10730.824513  ...  1566.827994  1072.45961
std     414.681806   3626.964585  ...   187.182436    52.64112
min       0.000000   4350.000000  ...  1300.000000  1000.00000
25%     358.750000   8450.000000  ...  1400.000000  1040.00000
50%     717.500000   9900.000000  ...  1600.000000  1070.00000
75%    1076.250000  11950.000000  ...  1600.000000  1085.00000
max    1435.000000  32500.000000  ...  2000.000000  1615.00000

[8 rows x 7 columns]

In [147]:
# print(df["FuelType"].unique())
# print(df[""])
for col in df.columns:
  print(col," => ",df[col].unique())

Unnamed: 0  =>  [   0    1    2 ... 1433 1434 1435]
Price  =>  [13500 13750 13950 14950 12950 16900 18600 21500 20950 19950 19600 22500
 22000 22750 17950 16750 16950 15950 16250 17495 15750 15500 14750 19000
 15800 21950 20500 13250 15250 18950 15999 16500 18750 22250 12995 18450
 16895 14900 17250 15450 16650 17450 16450 18900 18990 18500 19450 18800
 32500 31000 31275 24950 22950 24990 17900 19250 16350 21750 15850 23000
 19900 23950 24500 17200 19500 16868 19750 20750 17650 17795 18245 23750
 18700 21125  6950  9500 11950  7750  4350  4750 11750 11900  9950 11495
 11250 10500 10450 11500 12500 10950 11450 11790 12450 11690 12750 11925
 12900 11650 10850  9940 13450 12495 12000 11480 14990 12850 11700 11895
 13875 12295 13995  9900 11990 10750 11695 11000 12400 12200 12695 14350
 10250  6500  6400  7000  8900  8500  8950  9250  9450  8250  4450  9000
  5150  7900 10900  9750 11290 10895 10995  9850  8695 10990  8750  9930
  9799  9700  9990  9475 10000 10495  9400  9650  9550 13000 

In [148]:
# From above we can see that fuel type,HP,metcolor have Nan types and Doors have 
# 'three','five' kind of data

In [149]:
# in km we have a ?? value
# in FuelType we have nan
# in HP we have ????
# in Doors we have 'three' 'five' ... etc
# in metcolor we have nan
# Age also has nan we can replace it with mean
# Rest all columns are OK

In [150]:
# Step-1 Cleaning KM column
df["KM"].replace('??',-1,inplace=True)

In [151]:
df["KM"] = df["KM"].astype(int)

In [152]:
df["KM"].replace(-1,np.nan,inplace=True)

In [153]:
df["KM"].fillna(int(df["KM"].mean(skipna=True)),inplace = True)

In [154]:
df["KM"]

0       46986.0
1       72937.0
2       41711.0
3       48000.0
4       38500.0
         ...   
1431    20544.0
1432    68647.0
1433    17016.0
1434    68647.0
1435        1.0
Name: KM, Length: 1436, dtype: float64

In [155]:

# Step - 2 Cleaning FuelType and generating one hot representations for the same
df["FuelType"].unique()

array(['Diesel', nan, 'Petrol', 'CNG'], dtype=object)

In [156]:
df["FuelType"].value_counts()

Petrol    1177
Diesel     144
CNG         15
Name: FuelType, dtype: int64

In [157]:
# As we can infer there are maximum petrol cars we replace all nan cars to petrol cars

In [158]:
df["FuelType"].fillna('Petrol',inplace=True)

In [159]:
df["FuelType"].unique()

array(['Diesel', 'Petrol', 'CNG'], dtype=object)

In [160]:
df["FuelType"].value_counts()

Petrol    1277
Diesel     144
CNG         15
Name: FuelType, dtype: int64

In [161]:
fuelDummies = pd.get_dummies(df["FuelType"])

In [162]:
# Now we drop the fuel type and concat fuelDummies

In [163]:
df.drop(["FuelType"],axis=1,inplace = True)

In [164]:
df.head()

Unnamed: 0  Price   Age       KM  ... Automatic    CC  Doors  Weight
0           0  13500  23.0  46986.0  ...         0  2000  three    1165
1           1  13750  23.0  72937.0  ...         0  2000      3    1165
2           2  13950  24.0  41711.0  ...         0  2000      3    1165
3           3  14950  26.0  48000.0  ...         0  2000      3    1165
4           4  13750  30.0  38500.0  ...         0  2000      3    1170

[5 rows x 10 columns]

In [165]:
df = pd.concat([df,fuelDummies],axis=1)
df.head()

Unnamed: 0  Price   Age       KM  HP  ...  Doors  Weight  CNG Diesel  Petrol
0           0  13500  23.0  46986.0  90  ...  three    1165    0      1       0
1           1  13750  23.0  72937.0  90  ...      3    1165    0      1       0
2           2  13950  24.0  41711.0  90  ...      3    1165    0      1       0
3           3  14950  26.0  48000.0  90  ...      3    1165    0      1       0
4           4  13750  30.0  38500.0  90  ...      3    1170    0      1       0

[5 rows x 13 columns]

In [166]:

# Step-3 Removing ???? in HP and replacing with mean
df["HP"].replace('????',-1,inplace=True)
df["HP"] = df["HP"].astype(int)
df["HP"].replace(-1,np.nan,inplace=True)
df["HP"].fillna(int(df["HP"].mean(skipna=True)),inplace = True)
df["HP"].unique() # Now we can see all nan are replaced with mean

array([ 90., 101., 192., 110.,  97.,  71., 116.,  98.,  69.,  86.,  72.,
       107.,  73.])

In [167]:

# Step-4 Door data in df
doorMapping = {'three':'3','four':'4','five':'5'}
df["Doors"].replace(doorMapping,inplace=True)

In [168]:
df["Doors"].value_counts()

5    674
3    622
4    138
2      2
Name: Doors, dtype: int64

In [169]:
df["Doors"] = df["Doors"].astype(int)

In [170]:
df["Doors"].unique()

array([3, 5, 4, 2])

In [171]:

# Step-5 Cleaning nan from met color column

In [172]:
df["MetColor"].value_counts()

1.0    868
0.0    418
Name: MetColor, dtype: int64

In [173]:
df["MetColor"].unique()

array([ 1., nan,  0.])

In [174]:
# Replacing nan with 1 as 1 is in majority
df["MetColor"].fillna(1.0,inplace=True)

In [175]:
df["MetColor"].unique()

array([1., 0.])

In [176]:
df["MetColor"].value_counts()

1.0    1018
0.0     418
Name: MetColor, dtype: int64

In [177]:
# Step-6 Cleaning age and replacing with mean
df["Age"].fillna(-1,inplace=True)
df["Age"] = df["Age"].astype(int)
df["Age"].replace(-1,np.nan,inplace=True)
df["Age"].fillna(int(df["Age"].mean(skipna=True)),inplace = True)
df["Age"].unique() # As we can see that all age is replaced with mean

array([23., 24., 26., 30., 32., 27., 25., 22., 31., 28., 29., 55., 20.,
       19., 17., 11., 18., 13., 14.,  4.,  8.,  7., 16., 15., 10., 12.,
        9.,  6.,  2.,  1., 43., 38., 40., 44., 41., 37., 39., 42., 35.,
       34., 33., 36., 53., 51., 54., 45., 48., 52., 49., 56., 50., 47.,
       46., 58., 68., 59., 62., 65., 67., 64., 60., 61., 66., 57., 63.,
       73., 79., 78., 74., 77., 69., 80., 76., 70., 71., 75., 72.])

In [178]:


# Finally
df.isna().sum()

Unnamed: 0    0
Price         0
Age           0
KM            0
HP            0
MetColor      0
Automatic     0
CC            0
Doors         0
Weight        0
CNG           0
Diesel        0
Petrol        0
dtype: int64

In [179]:
for col in df.columns:
  print(col," => ",df[col].unique())


Unnamed: 0  =>  [   0    1    2 ... 1433 1434 1435]
Price  =>  [13500 13750 13950 14950 12950 16900 18600 21500 20950 19950 19600 22500
 22000 22750 17950 16750 16950 15950 16250 17495 15750 15500 14750 19000
 15800 21950 20500 13250 15250 18950 15999 16500 18750 22250 12995 18450
 16895 14900 17250 15450 16650 17450 16450 18900 18990 18500 19450 18800
 32500 31000 31275 24950 22950 24990 17900 19250 16350 21750 15850 23000
 19900 23950 24500 17200 19500 16868 19750 20750 17650 17795 18245 23750
 18700 21125  6950  9500 11950  7750  4350  4750 11750 11900  9950 11495
 11250 10500 10450 11500 12500 10950 11450 11790 12450 11690 12750 11925
 12900 11650 10850  9940 13450 12495 12000 11480 14990 12850 11700 11895
 13875 12295 13995  9900 11990 10750 11695 11000 12400 12200 12695 14350
 10250  6500  6400  7000  8900  8500  8950  9250  9450  8250  4450  9000
  5150  7900 10900  9750 11290 10895 10995  9850  8695 10990  8750  9930
  9799  9700  9990  9475 10000 10495  9400  9650  9550 13000 

In [180]:
df.head(5)

Unnamed: 0  Price   Age       KM    HP  ...  Doors  Weight  CNG  Diesel  Petrol
0           0  13500  23.0  46986.0  90.0  ...      3    1165    0       1       0
1           1  13750  23.0  72937.0  90.0  ...      3    1165    0       1       0
2           2  13950  24.0  41711.0  90.0  ...      3    1165    0       1       0
3           3  14950  26.0  48000.0  90.0  ...      3    1165    0       1       0
4           4  13750  30.0  38500.0  90.0  ...      3    1170    0       1       0

[5 rows x 13 columns]